// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "c6cf79de-bdad-491b-a274-0ef74cb77d6b");
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1629715739);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1629716099);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1629715979);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1629715859);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1629715770);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1629715709);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{3bb43f7f-569a-491a-9ac0-1bde8bf5987d}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.runOncePerModification.displayBookmarksToolbar", "false");
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1629715892739");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1629717710739");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1629715782129");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1629737382129");
user_pref("browser.search.region", "IN");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1629715732");
user_pref("browser.slowStartup.averageTime", 19372);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20210412162915");
user_pref("browser.startup.homepage_override.mstone", "78.10.0");
user_pref("browser.startup.lastColdStartupCheck", 1629715719);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("distribution.Kali.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "78.10.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "555aa7c22aff411ab3da2a719363c447");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "78.10.0");
user_pref("extensions.lastPlatformVersion", "78.10.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"afdd7d83-a2ce-4b41-9a59-17f9c8415e19\",\"formautofill@mozilla.org\":\"18961ca0-d5c1-4bdf-b12c-ae4e293e816c\",\"screenshots@mozilla.org\":\"e3fa4a7c-b301-46f8-9ca6-4f5add0cc920\",\"webcompat-reporter@mozilla.org\":\"8e30fc4a-fcaf-45af-a4eb-030feff01e84\",\"webcompat@mozilla.org\":\"222f5242-9f65-4a32-9083-4d4a7b7c98fa\",\"default-theme@mozilla.org\":\"50d913f0-2dac-42c8-9f36-6aa2c7489ada\",\"google@search.mozilla.org\":\"7f6c3f71-693b-455a-ab7e-9dc27f391b8a\",\"amazondotcom@search.mozilla.org\":\"a40f6cea-ca7a-4fd8-ab0e-108673abaf51\",\"wikipedia@search.mozilla.org\":\"40eaaee7-7057-46ac-be94-4e2834ec6325\",\"bing@search.mozilla.org\":\"3ae7dcb0-c11c-424f-806f-54924cd5fbea\",\"ddg@search.mozilla.org\":\"db4232cb-530a-4496-a786-09c050b456fd\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp-manager.buildID", "20210412162915");
user_pref("media.gmp-manager.lastCheck", 1629715776);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 66697);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.remote_settings.crlite_filters.checked", 1629717516);
user_pref("security.remote_settings.intermediates.checked", 1629717516);
user_pref("security.sandbox.content.tempDirSuffix", "8c6c0c4d-8679-4cf6-abd8-156a3b204e96");
user_pref("security.sandbox.plugin.tempDirSuffix", "55bc3cd1-03c7-4053-9202-2cd73c887efe");
user_pref("services.blocklist.addons-mlbf.checked", 1629717516);
user_pref("services.blocklist.gfx.checked", 1629717516);
user_pref("services.blocklist.pinning.checked", 1629717516);
user_pref("services.blocklist.plugins.checked", 1629717516);
user_pref("services.settings.clock_skew_seconds", -1743);
user_pref("services.settings.last_etag", "\"1629705463487\"");
user_pref("services.settings.last_update_seconds", 1629717516);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1629717516);
user_pref("services.settings.main.cfr-fxa.last_check", 1629717516);
user_pref("services.settings.main.cfr.last_check", 1629717516);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1629717516);
user_pref("services.settings.main.hijack-blocklists.last_check", 1629717516);
user_pref("services.settings.main.language-dictionaries.last_check", 1629717516);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1629717516);
user_pref("services.settings.main.public-suffix-list.last_check", 1629717516);
user_pref("services.settings.main.search-config.last_check", 1629717516);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1629717516);
user_pref("services.settings.main.sites-classification.last_check", 1629717516);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1629717516);
user_pref("services.settings.main.whats-new-panel.last_check", 1629717516);
user_pref("services.settings.security.onecrl.checked", 1629717516);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1629715700);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20210412162915");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
